### ISSUE TITLE
Support light home assistant component

### ISSUE THREAD

**Issue by tobiasdiez** [TheStaticTurtle/Open433#5]
It would be nice to have support for `light` components in home assistant. I'll open a PR for this, but wanted to ask you if you already have coded something in that direction.

Moreover, I wanted to ask what the config should look like. I guess most 433Mhz devices don't support continuous brightness changes. Thus I would propose something like the following
```
brightness:
   step:
       value: 10
       code:  Decimal code to set brightness to 10%
   step:
       value: 40
       code: ...
```
and for the devices that only have a lighter/darker controls:
```
brightness:
   lighter-code: Decimal code
   darker-code: Decimal code
   step: 20 (how much percentage the lighter/darker code change the brightness, e.g 20 -> 40)
```
